### ISSUE TITLE
支持以文件形式导入special-list/bypass-list # support import special-list/bypass-list from file 

### ISSUE THREAD

**Issue by ikidou** [honwen/aiodns#4]
我觉得这个项目很不错，但是在使用的过程中有一点点不太方便的地方是，如果白名单/黑名单域名比较多的情况下，使用参数的形式指定不太灵活，希望可以加入以文件的形式导入。比如可以参考 `curl`对于文件和非文件的处理：如果是以`@`开头则认为是一个文件，其他情况是为非文件。

**Comment by honwen** [comment]
https://github.com/honwen/aiodns/blob/829459c40b4b0664248598edd15195f0222380fe/main.go#L46

**Comment by ikidou** [comment]
OK，之前试用过一次，我还以为是每个special-list/bypass-list 是一个域名，每个域名重复一次，原来本来就是一个文件。感觉可以在help里给个说明，比如描述里加一个`... from local or net`，或者在文档里添加一下相关描述
